### PR TITLE
Struct support, performance adjustments and some utilities 

### PR DESCRIPTION
**Pull request by genaray**
## Background

Im using this library for my game server which uses a data oriented design heavily. Therefore i primarily use pure structs. Those have a lot of advantages, especially they require no memory allocation which is great for intensive quadtree operations. However this lib isnt supporting structs as quadtree objects properly, 

The .GetObject methods are not that great for hot paths, they either require a list which items can not be pre allocated or they offer just a simple action which we can not pass a payload to. In my case this made the queries pretty memory alloc heavy. Furthermore the .Move methods were never intended to work with structs aswell, so i couldnt properly move my quad objects properly which resulted into a "first remove than add" operation to simulate movement. 

## Improvements

Therefore i added a bunch of features into the project and improved/changed some code. 

- `.ObjectCounts(rect);` Is a new method which counts the amount of objects inside a given rectangle and returns its value
- `GetObjects(rect, Span<T> array)` Is a new method which copies all entities within the rect to a pre allocated array ( can also be stack allocated, great for performance ), should make use of the `ObjectCount` method before to allocate an array with the right size
- `GetObjects(rect, Action<T>)` methods were changes to `GetObjects(rect, ForObject<ref T>())` methods which make use of a delegate and references to avoid unecessary object copies and provide direct acess to the entity itself.
- `GetObjects<P>(rect, ForObject<ref P, ref T>())` was added to avoid closure copies and allow passing data to the delegate which than can be used upon the entity. In my case i needed it to cound entities of a certain type inside the quadtree which now can be done easily. 

Also several `MethodImpl` were added before the hot path methods to improve performance by inlining them properly.
I should also notice that using refs is way faster than using ins, ins do always create a security copy and are therefore slower. 

## Tests

Added a few more tests for my extensions i made, all tests do run properly without any issues,
All in all, this request can be accepted without hesitation... but would be great if you could look at the code to tell me if it fits your standards :) 

## Outlook
I havent looked that deep into this lib, but its the only one that fits my needs... so i hope for further performance improvements in the future to squeeze every bit of cpu and ram useage out of this ^^

### CODE REVIEW

**Comment by splitice** [comment]
I can see you have put in alot of work here.

I'm unsure about GetObjects since in order to pre allocate a array you need to know the searcg result size.

1. How are under and over cases handled? 
2. Are two quad tree searches (first to get the count) really more performant than either a list add or inline processing of the search results (usually the most optimal).


Can you please confirm there is no performance penalty with ref and class/object type objects. There used to be, but there has been many compiler versions since I last verified that quirk.

**Comment by genaray** [comment]
> I can see you have put in alot of work here.
> 
> I'm unsure about GetObjects since in order to pre allocate a array you need to know the searcg result size.
> 
> 1. How are under and over cases handled?
> 2. Are two quad tree searches (first to get the count) really more performant than either a list add or inline processing of the search results (usually the most optimal).
> 
> Can you please confirm there is no performance penalty with ref and class/object type objects. There used to be, but there has been many compiler versions since I last verified that quirk.

Thanks for your fast reply :) Well I just considered your concers and did some research. First of all, refs and classes are really a bit slower since the class pointer is being copied again which results in one unecessary copy per class being passed. Most people actually told me its not noticeable, but i solved this issue by providing two more delegates and method overloads.

Now you can either pick between overloads for struct usage and for class useage to push the queries to the limits. This requires the users attention, but this shouldnt be a problem since most people should now if they use Structs or Classes as their quadtree objects.  They could also use the class overload for structs or the struct overload for classes as they wish. The `GetObjects(rect, list)` method actually now checks whether the generic is a value type or class type and picks the fitting delegate ^^ 

Regarding the new `GetObjects(rect, arraySpan)` method, its actually pretty usefull. Its intention is to provide an alternative to lists. Arrays can be pooled and stack allocated which actually makes them faster than the `GetObject(rect, list)` approach since no allocations are required :) Especially in application hotpaths, in my example i use the `GetObject(rect, arraySpan)` and `ObjectCount(rect´)` methods every frame to check collisions and manage the "Area of Interest" around the player and other entities. I can not waste performance by using lists here since this allocates memory during the frame which slows down the performance a lot and results in gc spikes. This isnt a problem for a "few" entities inside the quadtree, but in my case there like thousands i need to check regulary so the `GetObjects(rect, arraySpan)` method comes in pretty handy to maximize effeciency here :)

**Comment by splitice** [comment]
> Especially in application hotpaths, in my example i use the GetObject(rect, arraySpan) and ObjectCount(rect´)

Surely `GetObjects(TQuery rect, Action<TObject> add)` would be faster than two distinct lookups. First to count then to fill.

Simply GetObjects and fill an an array that you allocate initially and then re-use via pool / statically within the controller scope (depending on threading / locking / memory requirements). We did that plenty in the hot paths of the application this library was built from.

**Comment by genaray** [comment]
> > Especially in application hotpaths, in my example i use the GetObject(rect, arraySpan) and ObjectCount(rect´)
> 
> Surely `GetObjects(TQuery rect, Action<TObject> add)` would be faster than two distinct lookups. First to count then to fill.
> 

Not necessary, it totally depends on what you are doing in that `GetObjects(rect, action)` method and what your goals are. When using delegates and lambdas you often run into using local variables which results in closure copies and bad performance after all. However this is fixed with the new payload mechanic. But we dont need to argue whether the `GetObjects(rect, arrayspan)` method is faster or not, it has its own use and is compatible with stackallocated arrays ^^

So are you planning to accept this ? Or is the new optional extension method such a deal breaker ?

**Comment by splitice** [comment]
I'm not likely to accept any PR proposed to improve performance that does not clearly provide a performance improvement.

Anyway I quickly tested your branch (with the aim of proving my previous statements) and found my statement to be correct. Actions remain the quickest way to execute the API generally (even more so if also doing radius or collision checks at this stage of processing).

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using QuadTrees;
using QuadTrees.QTreeRectF;

namespace ConsoleApp2
{
    struct QTreeObject: IRectFQuadStorable
    {
        public RectangleF Rect { get; set; }

        public QTreeObject(RectangleF rect)
        {
            Rect = rect;
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            QuadTreeRectF<QTreeObject> qtree = new QuadTreeRectF<QTreeObject>(-100000, -10000, 10000000, 1000000);
            qtree.AddRange(new List<QTreeObject>
            {
                new QTreeObject(new RectangleF(10,10,10,10)),
                new QTreeObject(new RectangleF(11,10,10,10)),
                new QTreeObject(new RectangleF(12,10,10,10)),
                new QTreeObject(new RectangleF(13,10,10,10)),
                new QTreeObject(new RectangleF(14,10,10,10)),
                new QTreeObject(new RectangleF(15,10,10,10)),
                new QTreeObject(new RectangleF(-1000,1000,10,10))
            });

            var arry = new QTreeObject[20];

            Stopwatch sw = new Stopwatch();
            sw.Start();
            for (int i = 0; i < 100000; i++)
            {
                var f = 0;
                qtree.GetObjects(new RectangleF(9, 9, 20, 20), a =>
                {
                    arry[f++] = a;

                    if (arry.Length == f)
                    {
                        Array.Resize(ref arry, arry.Length * 2);
                    }
                });

                // f can be used for making an array span or doing whatever with the results
            }
            Console.WriteLine("Elapsed using cb {0}", sw.Elapsed);

            sw.Reset();
            sw.Start();

            for (int i = 0; i < 100000; i++)
            {
                var f = 0;
                var search = new RectangleF(9, 9, 20, 20);
                Span<QTreeObject> qtSpan = new Span<QTreeObject>(arry, 0, qtree.ObjectCount(search));
                qtree.GetObjects(search, qtSpan);

                // can do something with qtSpan
            }
            Console.WriteLine("Elapsed using qtSpan {0}", sw.Elapsed);
        }
    }
}

```

It's a crude example but you would be better to use a delegate, and to re-use / pool the array allocation (buffer pool style).

The Callback based implementation is about 30% faster and thats without writing it in a particularly efficient manner.

**Pull request closed without merging**
